### ISSUE TITLE
Operation without editor popup

### ISSUE THREAD

**Issue by rsimon** [recogito/recogito-connections#11]
'Headless' mode, like for RecogitoJS/Annotorious

**Comment by reckart** [comment]
Still would be nice to have this 'headless' mode for the connections plugin. I'd say if the main recogito into which this plugins in runs in 'headless', then the connections should also run 'headless' by default.

**Comment by reckart** [comment]
There even is a comment in the code already:

```
    // TODO if (config.useEditor)
    mountEditor(this.canvas, this, config); 
```

How about changing that to:

```
   if (!Object.hasOwn(config, 'useEditor') || config.useEditor) {
      mountEditor(this.canvas, this, config); 
   }
```

**Comment by rsimon** [comment]
Agreed. But to be consistent with RecogitoJS's init params, I think I'd prefer inverting the behavior (despite my own comment ;-) 

How about an init option `disableEditor`? And then:

```js
if (!config.disableEditor)
  mountEditor(this.canvas, this, config);
```
