### ISSUE TITLE
Relation drawn twice

### ISSUE THREAD

**Issue by reckart** [recogito/recogito-connections#15]
When trying recogitojs (1.8.0) with the connections plugin (0.1.3), the relations get drawn twice:

<img width="154" alt="Screenshot 2022-09-17 at 17 12 51" src="https://user-images.githubusercontent.com/1410238/190863863-32cf425e-3ab5-4567-94ee-979b568d5e4e.png">

**Comment by rsimon** [comment]
Yikes - indeed, can confirm. This seems to happen only when the relationship annotation has a `body` payload. I'm investigating...
