### ISSUE TITLE
Ability to handle connections across independently scrolling areas

### ISSUE THREAD

**Issue by reckart** [recogito/recogito-connections#17]
I have a use-case here were we would like to annotate relations across two independently scrolling areas of a HTML page.

The plain connections support in recogito-js kind of handles the situation:

![Screenshot 2022-10-11 at 12 10 24](https://user-images.githubusercontent.com/1410238/195063999-e012e610-e2b6-4c73-abf7-2d5b52f15be8.png)

... unfortunately, the connection remains locked in space when scrolling:

![Screenshot 2022-10-11 at 12 15 03](https://user-images.githubusercontent.com/1410238/195064165-47d6016f-e12f-4967-bfb2-e2bb6f46f41d.png)

But with the connections plugin here, the connection does not show up at all. Instead, I get an error in the JS console:

```
main.esm.js:999 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'bvEnd')
    at calcInclusionForNotIntersectedFaces (main.esm.js:999:57)
    at filterNotRelevantEdges (main.esm.js:875:5)
    at booleanOpBinary (main.esm.js:947:5)
    at Object.unify (main.esm.js:768:32)
    at NetworkNode.js:19:30
    at Array.reduce (<anonymous>)
    at mergePolygons (NetworkNode.js:18:15)
    at get faces [as faces] (NetworkNode.js:67:31)
    at NetworkNode.getAttachableRect (NetworkNode.js:94:15)
    at SVGEdge.redraw (SVGEdge.js:91:39)
```

**Comment by rsimon** [comment]
Interesting. Are there two different Recogito instances running? I.e. one Recogito instance per scrolling pane? (I'm suprised that this works!)

In principle, the connections plugin should be a better basis to build something like this. (Supporting connections across different Recogito instances was one of the reasons I started it.) The error doesn't ring a bell, to be honest. Would you mind setting up an example on a JSFiddle or similar?

**Comment by reckart** [comment]
No, only a single instance on the parent element that contains the two scrolling regions.

**Comment by rsimon** [comment]
Ok, that explains it. Hm, this should be fixable I guess. Right now, RecogitoJS listens to window resize events, and will recompute all connections when the window resizes:

https://github.com/recogito/recogito-js/blob/main/src/relations/RelationsLayer.js#L30-L32

This was assuming that window resize is usually the only action that requires a redraw. The challenge, I guess, would be identify _any_ change to the layout, and then also trigger a redraw. Maybe placing a MutationObserver at the top of the DOM element that's annotated by RecogitoJS?

**Comment by reckart** [comment]
> Maybe placing a MutationObserver at the top of the DOM element that's annotated by RecogitoJS?

Would that take note of scrolling events? I mean, scrolling doesn't really change the DOM.

**Comment by rsimon** [comment]
Good point. Hm, then it's probably trickier. Find all scrollable elements and redraw on scroll? As a workaround, perhaps have some kind of config mechanism in the future, so that scroll listeners could be attached to elements that are specifically configured from the outside?

**Comment by reckart** [comment]
One listener on the top-element? cf. https://stackoverflow.com/a/32954565/2511197

**Comment by rsimon** [comment]
Ah - yes, sounds good & should make the change fairly straightforward.

**Comment by reckart** [comment]
Hm, actually it seems to work in some cases with the connections plugin without the error I posted above.

https://user-images.githubusercontent.com/1410238/195125783-13f72c08-a661-44d9-9d7b-cf3f21736cd8.mp4

**Comment by reckart** [comment]
@rsimon could this error be related to recogito's behavior of rendering the highlights in chunks using some setTimeout/requestAnimationFrame approach?

```
main.esm.js:999 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'bvEnd')
    at calcInclusionForNotIntersectedFaces (main.esm.js:999:57)
    at filterNotRelevantEdges (main.esm.js:875:5)
    at booleanOpBinary (main.esm.js:947:5)
    at Object.unify (main.esm.js:768:32)
    at NetworkNode.js:19:30
    at Array.reduce (<anonymous>)
    at mergePolygons (NetworkNode.js:18:15)
    at get faces [as faces] (NetworkNode.js:67:31)
    at NetworkNode.getAttachableRect (NetworkNode.js:94:15)
    at SVGEdge.redraw (SVGEdge.js:91:39)
```

Maybe the connections plugin can be triggered to render before all the chunks have been rendered?

**Comment by rsimon** [comment]
Hm, I'd need more time to dig into this. It seems to happen in flatten js [here](https://github.com/alexbol99/flatten-js/blob/b18653301f6a1e08e4c377decc4a3598cf5ac808/src/algorithms/boolean_op.js#L263), i.e. something where the individual "faces" (the rectangles corresponding to each of the highlight boxes of a multi-line annotation) get merged. Are you doing anything specific, like dynamic removal/lazy loading of annotations as the enter or leave the viewport?

**Comment by reckart** [comment]
Not really, why?

**Comment by rsimon** [comment]
My initial suspicion was that there might be a timing issue where bbox information is fetched from a DOM element that no longer exists. Because things break when computing the  "attachableRect", i.e. the area the arrow is supposed to snap to. But really just stabbing in the dark here...

**Comment by reckart** [comment]
Well, it is entirely possible that a reload of the annotation is triggered while the rendering is still in progress in particular since the rendering in recogito is async. Is there a way to disable the async strategy and make sync it or alternatively to use some `.then(...)` to get a notification when rendering is complete?
