### ISSUE TITLE
Problem rendering connections

### ISSUE THREAD

**Issue by reckart** [recogito/recogito-connections#18]
On certain constellations of span annotations, the rendering of connections fails. 

E.g. if we have a span annotation that is represented by elements with the following coordinates:

<img width="216" alt="Screenshot 2022-11-01 at 19 35 51" src="https://user-images.githubusercontent.com/1410238/199311569-d7b9e864-d231-4346-92d4-3c8b6c14cca9.png">

Then `NetworkNode.mergePolygons` produces an empty list of faces:

<img width="1388" alt="Screenshot 2022-11-01 at 19 37 17" src="https://user-images.githubusercontent.com/1410238/199311892-a90acdf1-d112-45fe-87c3-890860765bd1.png">

This later causes the rendering of the edge to fail.

**Comment by reckart** [comment]
Actually, the creation of zero-width annotation elements should probably already be suppressed in the main recogito-js code.

<img width="435" alt="Screenshot 2022-11-01 at 19 40 10" src="https://user-images.githubusercontent.com/1410238/199312391-3883b4d8-93ce-45a7-b912-2fdab347625d.png">

**Comment by rsimon** [comment]
Thanks for debugging this! I agree: zero-width annotation spans shouldn't occur. The PR is a good workaround for the time being though. I'll open a ticket in the RecogitoJS issue tracker, so this remains on the list.
